dex:
  clientID: example-app
  issuerURL: "http://dex/dex"

server:
  port: 5555

kubeConfig: "/Users/poke/.kube/config"

log:
  level: 4
  format: "json"
  noColor: true

customGroups:
- groupName: developers
  customRules:
  - verbs: [ "get", "list" ]
    resources: [ "deployments", "replicasets", "pods" ]
    apiGroups: [ "", "extensions", "apps" ]
