dex:
  clientID: "example-app"
  issuerURL: "http://localhost/dex"
server:
  port: "5555"
customGroups:
- groupName: developers
  customRules:
  - verbs: [ "get", "list" ]
    resources: [ "deployments", "replicasets", "pods" ]
    apiGroups: [ "", "extensions", "apps" ]
